### PR TITLE
Turbolinks

### PR DESCRIPTION
**Pull request by skylar-anderson**

### CODE REVIEW

**Comment by gib** [comment]
😱 ❗ ❗ ❗

**Comment by fancyremarker** [comment]
Much faster! I did notice this glitch on staging with Swiftype autocompletion, not sure if it's related: 
swiftype-overlap

**Comment by skylar-anderson** [comment]
Thanks for the GIF @fancyremarker .  This was caused by me leaving our segment and swiftype installs in the footer of the document.  Each time you visit a page, Turbolinks would re-add this JS and "reinstall" swiftype using the same element selectors.  The fix was to simply move the installation to the head, so that it is only ever installed once. 

Everything seems to be 👍 so I'll merge.

**Comment by fancyremarker** [comment]
Thanks @sandersonet ! Checked and confirmed what I saw is now fixed.

**Pull request merged**
