### PR TITLE
Document HTTPS Log Drains

### PR DESCRIPTION
**Pull request by krallin**
We shipped this a little while ago. It'd probably be worth documenting! : )

See: https://github.com/aptible/docker-logstash/pull/2

### CODE REVIEW

**Comment by wcpines** [comment]
CC @fancyremarker for feedback.  

My $0.02: 
- Though I like it, the tone may be inconsistent with rest of docs
- Could step 1 use any more detail?
- Nix big headings to sections

**Comment by fancyremarker** [comment]
@wcpines: I'm fine with the tone of this article; as for headings, perhaps we should use h2 for consistency w/ e.g. [aptible-docker-images.md](https://github.com/aptible/support/blob/master/source/topics/paas/aptible-docker-images.md).

**Comment by krallin** [comment]
@fancyremarker @wcpines 

Thanks for the heads up regarding the headings. Updated them to h2. Also fixed the merge conflict we had with master.

I think step 1 actually has a good amount of detail provided in the Logstash repo's README, but let me know if you think that's not enough.

Cheers,

**Comment by wcpines** [comment]
:+1:

**Pull request merged**
