### PR TITLE
Toolbelt download page

### PR DESCRIPTION
**Pull request by skylar-anderson**

### CODE REVIEW

**Comment by krallin** [comment]
Thanks a lot for your work on this @sandersonet; here are a few notes / comments:

Minor nit: right now for EL, you have EL 6 / EL **8**. The versions are actually EL 6 / EL **7**.

Regarding how we update the references. I can see they're specified in a YAML file right now. I think this is probably good enough for now, and I think I might be able to automate PRs for this. Alternatively we might be able to store this in a static JSON, serve it via S3 (using CORS), and create the page on the fly. Let me know what you think works best (I imagine that'll the best first option — as I mentioned I think it's reasonable). If we do decide to stick with the YAML file, we might want to remove point versions from there for Debian CentOS, OSX (we'll only ever have one OSX package).

Regarding the installation instructions. Currently, they reference a package name (which also happens to be URL-escaped, but that won't be the case for the downloaded file), but the package name is going to be different between the two packages we allow downloading. 

Should we just replace them with a more generic set of instructions, e.g.: 
- OSX: Double click the downloaded package and follow the instructions.
- Any Linux: Use your package manager (graphical or command line) and install the package. You'll need to use `sudo` to elevate your permissions.

(if you find a way to retain the instructions, we need to update the EL instructions to use `rpm` not `dpkg`).

Can we provide the full URLs to the releases on the page? (perhaps even behind a click) For someone installing via the CLI, it's a little more convenient than having to right-click.

Finally, ordering-wise, OSX | Ubuntu | Debian | EL might correspond to our audience better than the current ordering.

Let me know if you'd like to get on a quick call to sort through this, it might be easier :)

Thanks again!

**Comment by fancyremarker** [comment]
> Regarding how we update the references.
> 
> I can see they're specified in a YAML file right now.

^^ I think this is the easiest immediate approach.

> Alternatively we might be able to store this in a static JSON, serve it via S3 (using CORS), and create the page on the fly. 

^^ If we automate, I think this is the cleanest automated approach.

**Comment by skylar-anderson** [comment]
@krallin Thanks for your feedback! I agree with all of your suggestions, so I went ahead and implemented them.  I also added a small github section with links to aptible/aptible-cli and aptible/omnibus-aptible-toolbelt

**Comment by krallin** [comment]
@sandersonet awesome; is this live somewhere I could check or should I build it locally?

Thanks!

**Comment by fancyremarker** [comment]
@krallin @sandersonet : I just pushed this branch up to [staging](https://support.aptible-staging.com/toolbelt) for review.

**Comment by fancyremarker** [comment]
It looks 🔥 🔥 🔥  hawt btw.

**Comment by gib** [comment]
Looks awesome @sandersonet! I did notice a few minor responsive issues on small screens -- clearly not blockers as I trust that there are close to zero users downloading a linux version of the toolbelt via mobile.
🔥 🔥 🔥 
:shipit:

**Comment by krallin** [comment]
@sandersonet a small request that would make auto-updating a bit simpler:
- Can we make the version key in the YAML include the `v` prefix, rather add it in the templates? (that's more consistent with the actual metadata in S3)

**Comment by krallin** [comment]
The auto-update mechanism is ready (caveat the note above), so we can ship this whenever you want : )

**Pull request merged**
